# 应用服务 WEB 访问端口
spring:
  datasource:
    ds1:
      jdbcUrl: jdbc:mysql://117.119.84.31:3306/sys?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: Cmis_2022@
    ds2:
      jdbcUrl: jdbc:mysql://localhost:3306/dslock?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
